services:
    backend-express:
        container_name: taufik-tickitz
        image: taufikharahap/tickitz-app:2
        restart: unless-stopped
        ports:
            - '8002:8001'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            - DB_HOST=host.docker.internal
            - DB_USER=taufik
            - DB_NAME=taufik_db
            - DB_PASSWORD=taufik
            - DB_PORT=5432
        networks:
            - gonet

networks:
    gonet:
        name: golang
        external: true