services:
    backend-express:
        container_name: taufik-tickitz
        image: taufikharahap/tickitz-app:3
        ports:
            - '8002:8001'
        environment:
            - DB_HOST=postgres
            - DB_USER=taufik
            - DB_NAME=taufik_db
            - DB_PASSWORD=taufik
            - DB_PORT=5432
        networks:
            - gonet

networks:
    gonet:
        name: golang
        external: true