services:
    backend-express:
        container_name: taufik-tickitz
        image: taufikharahap/tickitz-app:3
        ports:
            - '8002:8001'
        environment:
            - DB_HOST=ep-sweet-sea-a1x9okiq.ap-southeast-1.aws.neon.tech
            - DB_USER=tickitz_db_owner
            - DB_NAME=tickitz_db
            - DB_PASSWORD=3mOl1ajQxgqn
            - DB_PORT=5432