CREATE TABLE public.movie (
   movie_id serial PRIMARY KEY,
   movie_name VARCHAR NOT NULL,
   movie_poster varchar NULL,
   release_date DATE NOT NULL,
   directed_by VARCHAR(50) NOT NULL,
   casts TEXT[] NOT NULL,
   duration INTERVAL NOT NULL,
   synopsis TEXT NOT NULL
);

INSERT INTO movie(movie_name, movie_poster, release_date, directed_by, casts, duration, synopsis)
VALUES
   ('Aquaman and the Lost Kingdom', 'https://www.google.com/40x40', 'Fantasy'], '2023-12-23'::date, 'James Wan', ARRAY['Jason Momoa', 'Patrick Wilson', 'Yahya Abdul-Mateen II', 'Randall Park'], '2 hours 4 minutes', 'Black Manta, still driven by the need to avenge his father''s death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction'),
   ('Wonka', 'https://www.google.com/40x40', ARRAY['Comedy', 'Family', 'Fantasy'], '2023-08-12'::date, 'Paul King', ARRAY['Timothée Chalamet', 'Calah Lane', 'Keegan-Michael Key', 'Hugh Grant'], '1 hours 57 minutes', 'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.'),
   ('Wish', 'https://www.google.com/40x40', ARRAY['Drama'], '2023-11-22'::date, 'Fawn Veerasunthorn', ARRAY['Ariana DeBose', 'Chris Pine', 'Alan Tudyk', 'Angelique Cabral'], '1 hours 35 minutes', 'Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.'),
   ('Migration', 'https://www.google.com/40x40', ARRAY['Adventure', 'Fantasy'], '2023-12-22'::date, 'Benjamin Renner', ARRAY['Kumail Nanjiani', 'Elizabeth Banks', 'Caspar Jennings', 'Tresi Gazal'], '1 hours 23 minutes', 'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.'),
   ('The Marvels', 'https://www.google.com/40x40', ARRAY['Action'], '2023-11-10'::date, 'Nia DaCosta', ARRAY['Brie Larson', 'Teyonah Parris', 'Iman Vellani', 'Zawe Ashton'], '1 hours 45 minutes', 'Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.'),
   ('Sixty Minutes', 'https://www.google.com/40x40', ARRAY['Action', 'Adventure'], '2024-01-19'::date, 'Oliver Kienle', ARRAY['Emilio Sakraya', 'Dennis Mojen', 'Marie Mouroum', 'Florian Schmidtke'], '1 hours 29 minutes', 'Demi mempertahankan hak asuh atas putrinya, seorang petarung MMA mengabaikan pertarungan besar dan bergegas melintasi Berlin untuk menghadiri ulang tahun putrinya itu.'),
   ('The Beekeeper', 'https://www.google.com/40x40', ARRAY['Sc-Fi', 'Adventure', 'Fantasy'], '2024-01-12'::date, 'David Ayer', ARRAY['Jason Statham', 'Emmy Raver-Lampman', 'Bobby Naderi', 'Josh Hutcherson'], '1 hours 45 minutes', 'One man''s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.'),
   ('Patriots Time', 'https://www.google.com/40x40', ARRAY['Sc-Fi'], '2022-04-28'::date, 'Serikbol Utepbergenov', ARRAY['Daniyar Alshinov', 'Sanurzhan Suleymenov', 'Dasten Shakirov', 'Sayat Isembayev'], '1 hours 41 minutes', 'The brothers Sultan and Bekzat Ibrayev are serving faithfully in the Armed Forces of Kazakhstan, and at the same time they are in family disagreement. Sultan is a valiant intelligence officer and Bekzat is a talented fighter pilot. While an international terrorist organization prepares a carefully planned attack on the country''s strategically important facilities, the brothers have to face not only a mortal threat, but also face a family confrontation related to their dead father. Circumstances force them to unite in order to save human lives, and the brothers eventually understand that their homeland and family are the most valuable thing they have.'),
   ('Radical', 'https://www.google.com/40x40', ARRAY['Crime'], '2022-11-03'::date, 'Christopher Zalla', ARRAY['Eugenio Derbez', 'Daniel Haddad', 'Jennifer Trejo', 'Mia Fernanda Solis'], '2 hours 7 minutes', 'In a Mexican border town plagued by neglect, corruption, and violence, a frustrated teacher tries a radical new method to break through his students’ apathy and unlock their curiosity, their potential… and maybe even their genius.'),
   ('Attack', 'https://www.google.com/40x40', ARRAY['Horror'], '2022-04-01'::date, 'Lakshya Raj Anand', ARRAY['John Abraham', 'Serena Walia', 'Rakul Preet Singh', 'Prakash Raj'], '2 hours 3 minutes', 'With the Parliament under siege, India’s first super soldier Arjun Shergill is tasked to get hold of the terrorists in the nick of time, save the Prime Minister from their clutches and stop a dirty bomb from exploding and destroying Delhi. Will Arjun succeed in his mission?'),
   ('Napole', 'https://www.google.com/40x40', ARRAY['Romance'], '2023-11-22'::date, 'Ridley Scott', ARRAY['Joaquin Phoenix', 'Vanessa Kirby', 'Rupert Everett', 'Mark Bonnar'], '2 hours 38 minutes', 'An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.');